# Generated by Django 5.0.2 on 2024-06-05 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='birth_date',
        ),
    ]
